obj-$(CONFIG_CRYPTO_DEV_ASPEED) += aspeed_hace.o
obj-$(CONFIG_CRYPTO_ACRY_ASPEED) += aspeed_acry.o
aspeed_hace-objs := aspeed-hace-main.o \
		      aspeed-hace-crypto.o \
		      aspeed-hace-hash.o \
		      aspeed-hace-rsa.o

aspeed_acry-objs := aspeed-acry-main.o \
		         aspeed-acry-rsa.o

